version: "3.8"
services:
  backend:
    environment:
      - DEPLOY=1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "~/music:/musicServer/music"
      - "./psw/:/musicServer/psw"
  frontend:
    build: ./frontEnd
    ports:
      - "5173:5173"
